version: "3.9"

services:
  mksdb-mariadb:
    image: "mariadb"
    ports:
      - "11006:3306"
    environment:
      - MYSQL_DATABASE=schlager
      - MYSQL_USER=schlager
      - MYSQL_PASSWORD=zorofzoftumev
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command: "mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./mariadb-data:/var/lib/mysql"

  mksdb-php:
    build:
      context: .
    ports:
      - "11080:80"
    volumes:
      - "../../:/var/www/priv"
      - "../../app-dist:/var/www/html/schlager"
      - "../../web:/var/www/html/schlager/api"
      - "../../htdocs-installer:/var/www/html/installer"
